version: '3'
services:
  nginx:
    image: nginx:1.21.3-alpine
    hostname: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '8080:443'

  goserver:
    image: alpine:3.14.2
    volumes:
      - .:/example
    command: /example/example
    environment:
      SERVER_URL: https://0.0.0.0:8080/v1
      SERVER_ADDR: 0.0.0.0:8080
